name: ruqayyah
description: A new Flutter project.
publish_to: "none"

version: 0.4.02+7

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  audioplayers: ^6.5.1
  bloc: ^9.1.0
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  get_it: ^8.2.0
  get_storage: ^2.1.1
  intl: ^0.20.2
  material_design_icons_flutter: ^7.0.7296
  path: ^1.9.1
  path_provider: ^2.1.5
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.6
  url_launcher: ^6.3.2
  vibration: ^3.1.4
  wakelock_plus: ^1.4.0
  window_manager: ^0.5.1

dev_dependencies:
  icons_launcher: ^3.0.3
  lint: ^2.3.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/db/
    - assets/sounds/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Uthmanic
      fonts:
        - asset: assets/fonts/uthmanic_hafs_ver12.otf
    - family: Uthmanic2
      fonts:
        - asset: assets/fonts/UthmanicHafs_v2-1.ttf
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
    - family: Kitab
      fonts:
        - asset: assets/fonts/kitab.ttf
flutter_intl:
  enabled: true
